### ISSUE TITLE
brew install codeclimate not compatible with dvm

### ISSUE THREAD

**Issue by klippx** [codeclimate/homebrew-formulae#22]
I am using dvm (https://github.com/getcarina/dvm) for switching between docker versions, which means my docker is not in the default path that your formulae assumes when it does the command `==> env PATH=/usr/local/bin:/usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin PREFIX=/usr/local/Cellar/codeclimate/0.19.0 make install`

If you need to modify the path, maybe it is better append whatever you need to the path instead of changing it altogether?

```
╰─○ brew install codeclimate
==> Installing codeclimate from codeclimate/formulae
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.19.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/codeclimate-0.19.0.tar.gz
==> env PATH=/usr/local/bin:/usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin PREFIX=/usr/local/Cellar/codeclimate/0.19.0 make install
Last 15 lines from /Users/mathias.klippinge/Library/Logs/Homebrew/codeclimate/01.env:
2016-02-11 08:48:56 +0100

env
PATH=/usr/local/bin:/usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin
PREFIX=/usr/local/Cellar/codeclimate/0.19.0
make
install

bin/check
Unable to find `docker' on your $PATH, is it installed?
make: *** [install] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/codeclimate/homebrew-formulae/issues

╰─○ which docker
/Users/mathias.klippinge/.dvm/bin/docker/1.9.1/docker

╰─○ env | grep PATH
PATH=/Users/mathias.klippinge/.rvm/gems/ruby-2.3.0/bin:/Users/mathias.klippinge/.rvm/gems/ruby-2.3.0@global/bin:/Users/mathias.klippinge/.rvm/rubies/ruby-2.3.0/bin:/Users/mathias.klippinge/.rvm/bin:/Users/mathias.klippinge/.dvm/bin/docker/1.9.1:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
```

**Comment by pbrisbin** [comment]
Hi @klippx 

> If you need to modify the path, maybe it is better append whatever you need to the path instead of changing it altogether?

Yes, we do exactly that (we prepend instead of append, but that shouldn't affect your case). [Source](https://github.com/codeclimate/homebrew-formulae/blob/master/Formula/codeclimate.rb#L15).

The issue you're running into is that the context in which Homebrew runs these formulae won't have the `$PATH` you may have customized for interactive shells. That's exactly why we have to do what we're doing to make any Homebrew-installed `docker` available.

I'm not sure if there's a viable workaround. It may be possible to tell Homebrew to use a custom environment, or to run these in an interactive shell. It might also work to move your custom `$PATH` setting from an interactive startup file (e.g. `.zshrc`) to a non-interactive one (e.g. `.zshenv` or `.zprofile`). Either way, I'm pretty sure there's nothing we can do within the formula itself to solve this issue for you.

I'll leave this open for a bit before closing, in case there's something I'm missing.

**Comment by klippx** [comment]
Allright, thanks. I managed to complete the installation by temporarily symlinking docker from the `/usr/local/Library/ENV/4.3` folder, and then removing it after installation. I think most people wont have this issue if they used `brew install docker` instead, so I'm OK with closing this.

**Comment by ibrahimdolapci** [comment]
`brew link docker` worked for me.
